//
//  GoogleLanguage.swift
//  baluchon
//
//  Created by pierrick viret on 28/08/2023.
//

import Foundation

enum GoogleLanguage {

    case language(String)

    var complete: String {
        switch self {
        case.language(let code):
            if let completLanguage = languageCodes[code] {
                return completLanguage
            } else {
                return "Anglais"
            }
        }
    }

    var code: String {
        switch self {
        case.language(let name):
            if let codeLanguage = languageNames[name] {
                return codeLanguage
            } else {
                return "en"
            }
        }
    }
}

let languageCodes: [String: String] = [
        "af": "Afrikaan",
        "sq": "Albanais",
        "am": "Amharique",
        "hy": "Arménien",
        "as": "Assamais",
        "ay": "Aymara",
        "az": "Azéri",
        "bm": "Bambara",
        "eu": "Basque",
        "be": "Biélorusse",
        "bn": "Bengalî",
        "bho": "Bhodjpouri",
        "bs": "Bosniaque",
        "bg": "Bulgare",
        "ca": "Catalan",
        "ceb": "Cebuano",
        "zh-CN": "Chinois",
        "zh-TW": "Chinois",
        "co": "Corse",
        "hr": "Croate",
        "cs": "Tchèque",
        "da": "Danois",
        "dv": "Divéhi",
        "doi": "Dogri",
        "nl": "Néerlandais",
        "en": "Anglais",
        "eo": "Espéranto",
        "et": "Estonien",
        "ee": "Ewe",
        "fil": "Filipino",
        "fi": "Finnois",
        "fr": "Français",
        "fy": "Frison",
        "gl": "Galicien",
        "ka": "Géorgien",
        "de": "Allemand",
        "el": "Grec",
        "gn": "Guarani",
        "gu": "Gujarâtî",
        "ht": "Créole haïtien",
        "ha": "Haoussa",
        "haw": "Hawaïen",
        "he": "Hébreu",
        "hi": "Hindi",
        "hmn": "Hmong",
        "hu": "Hongrois",
        "is": "Islandais",
        "ig": "Igbo",
        "ilo": "Ilocano",
        "id": "Indonésien",
        "ga": "Irlandais",
        "it": "Italien",
        "ja": "Japonais",
        "jv": "Javanais",
        "kn": "Kannara",
        "kk": "Kazakh",
        "km": "Khmer",
        "rw": "Kinyarwanda",
        "gom": "Konkani",
        "ko": "Coréen",
        "kri": "Krio",
        "ku": "Kurde",
        "ckb": "Kurde",
        "ky": "Kirghyz",
        "lo": "Laotien",
        "la": "Latin",
        "lv": "Letton",
        "ln": "Lingala",
        "lt": "Lituanien",
        "lg": "Luganda",
        "lb": "Luxembourgeois",
        "mk": "Macédonien",
        "mai": "Maithili",
        "mg": "Malgache",
        "ms": "Malais",
        "ml": "Malayâlam",
        "mt": "Maltais",
        "mi": "Maori",
        "mr": "Marathi",
        "mni-Mtei": "Meitei",
        "lus": "Mizo",
        "mn": "Mongol",
        "my": "Birman",
        "ne": "Népalais",
        "no": "Norvégien",
        "ny": "Nyanja",
        "or": "Odia",
        "om": "Oromo",
        "ps": "Pachtô",
        "fa": "Perse",
        "pl": "Polonais",
        "pt": "Portugais",
        "pa": "Panjabi",
        "qu": "Quechua",
        "ro": "Roumain",
        "ru": "Russe",
        "sm": "Samoan",
        "sa": "Sanskrit",
        "gd": "Gaélique",
        "nso": "Sepedi",
        "sr": "Serbe",
        "st": "Sesotho",
        "sn": "Shona",
        "sd": "Sindhî",
        "si": "Singhalais",
        "sk": "Slovaque",
        "sl": "Slovène",
        "so": "Somali",
        "es": "Spanish",
        "su": "Soundanais",
        "sw": "Swahili",
        "sv": "Suédois",
        "tl": "Tagalog",
        "tg": "Tadjik",
        "ta": "Tamoul",
        "tt": "Tatar",
        "te": "Télougou",
        "th": "Thaï",
        "ti": "Tigrinya",
        "ts": "Tsonga",
        "tr": "Turc",
        "tk": "Turkmène",
        "ak": "Twi",
        "uk": "Ukrainien",
        "ur": "Urdu",
        "ug": "Ouïghour",
        "uz": "Ouzbek",
        "vi": "Vietnamien",
        "cy": "Gallois",
        "xh": "Xhosa",
        "yi": "Yiddish",
        "yo": "Yoruba",
        "zu": "Zoulou"
    ]

let languageNames: [String: String] = [
    "Afrikaan": "af",
    "Albanais": "sq",
    "Amharique": "am",
    "Arménien": "hy",
    "Assamais": "as",
    "Aymara": "ay",
    "Azéri": "az",
    "Bambara": "bm",
    "Basque": "eu",
    "Biélorusse": "be",
    "Bengalî": "bn",
    "Bhodjpouri": "bho",
    "Bosniaque": "bs",
    "Bulgare": "bg",
    "Catalan": "ca",
    "Cebuano": "ceb",
    "Chinois": "zh-CN",
    "Corse": "co",
    "Croate": "hr",
    "Tchèque": "cs",
    "Danois": "da",
    "Divéhi": "dv",
    "Dogri": "doi",
    "Néerlandais": "nl",
    "Anglais": "en",
    "Espéranto": "eo",
    "Estonien": "et",
    "Ewe": "ee",
    "Filipino": "fil",
    "Finnois": "fi",
    "Français": "fr",
    "Frison": "fy",
    "Galicien": "gl",
    "Géorgien": "ka",
    "Allemand": "de",
    "Grec": "el",
    "Guarani": "gn",
    "Gujarâtî": "gu",
    "Créole haïtien": "ht",
    "Haoussa": "ha",
    "Hawaïen": "haw",
    "Hébreu": "he",
    "Hindi": "hi",
    "Hmong": "hmn",
    "Hongrois": "hu",
    "Islandais": "is",
    "Igbo": "ig",
    "Ilocano": "ilo",
    "Indonésien": "id",
    "Irlandais": "ga",
    "Italien": "it",
    "Japonais": "ja",
    "Javanais": "jv",
    "Kannara": "kn",
    "Kazakh": "kk",
    "Khmer": "km",
    "Kinyarwanda": "rw",
    "Konkani": "gom",
    "Coréen": "ko",
    "Krio": "kri",
    "Kurde": "ckb",
    "Kirghyz": "ky",
    "Laotien": "lo",
    "Latin": "la",
    "Letton": "lv",
    "Lingala": "ln",
    "Lituanien": "lt",
    "Luganda": "lg",
    "Luxembourgeois": "lb",
    "Macédonien": "mk",
    "Maithili": "mai",
    "Malgache": "mg",
    "Malais": "ms",
    "Malayâlam": "ml",
    "Maltais": "mt",
    "Maori": "mi",
    "Marathi": "mr",
    "Meitei": "mni-Mtei",
    "Mizo": "lus",
    "Mongol": "mn",
    "Birman": "my",
    "Népalais": "ne",
    "Norvégien": "no",
    "Nyanja": "ny",
    "Odia": "or",
    "Oromo": "om",
    "Pachtô": "ps",
    "Perse": "fa",
    "Polonais": "pl",
    "Portugais": "pt",
    "Panjabi": "pa",
    "Quechua": "qu",
    "Roumain": "ro",
    "Russe": "ru",
    "Samoan": "sm",
    "Sanskrit": "sa",
    "Gaélique": "gd",
    "Sepedi": "nso",
    "Serbe": "sr",
    "Sesotho": "st",
    "Shona": "sn",
    "Sindhî": "sd",
    "Singhalais": "si",
    "Slovaque": "sk",
    "Slovène": "sl",
    "Somali": "so",
    "Spanish": "es",
    "Soundanais": "su",
    "Swahili": "sw",
    "Suédois": "sv",
    "Tagalog": "tl",
    "Tadjik": "tg",
    "Tamoul": "ta",
    "Tatar": "tt",
    "Télougou": "te",
    "Thaï": "th",
    "Tigrinya": "ti",
    "Tsonga": "ts",
    "Turc": "tr",
    "Turkmène": "tk",
    "Twi": "ak",
    "Ukrainien": "uk",
    "Urdu": "ur",
    "Ouïghour": "ug",
    "Ouzbek": "uz",
    "Vietnamien": "vi",
    "Gallois": "cy",
    "Xhosa": "xh",
    "Yiddish": "yi",
    "Yoruba": "yo",
    "Zoulou": "zu"
]
